name: Contract CI
on:
  push:
    branches:
      - main
    paths:
      - "contract_/**"
  pull_request:
    paths:
      - "contract_/**"

defaults:
  run:
    working-directory: contract_

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    name: Cairo formatting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contract_/.tool-versions
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: contract_/.tool-versions
      - name: Check Scarb Formatting
        run: scarb fmt --check
  run-test:
    runs-on: ubuntu-latest
    name: Cairo test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contract_/.tool-versions
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: contract_/.tool-versions
      - name: Run scarb test
        run: scarb test