name: Frontend CI

on:
  pull_request:
    paths:
      - 'webapp/**'
      - 'dashboard/**'

jobs:
  build-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # Or your preferred pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

  build-dashboard:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dashboard

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # Or your preferred pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
